import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import kleur from "kleur";
import {
  parseSkillFile,
  COMPILERS,
  findSkillFiles,
  loadConfig,
  CROSSKILL_VERSION,
  LOCKFILE_NAME,
  LOCKFILE_VERSION,
  diffLockfiles,
  readLockfile,
  sha256,
  toPosixPath,
  writeLockfile,
  type Lockfile,
  type LockDrift,
  type SkillLockEntry,
  type CompileResult,
  type Skill,
  type SupportedTarget,
} from "@crosskill/core/node";

interface BuildOptions {
  cwd?: string;
  configPath?: string;
  /** Verify outputs match crosskill.lock; do not write. CI mode. */
  frozen?: boolean;
}

interface SkillSource {
  skill: Skill;
  sourceBytes: Buffer;
}

interface BuildPlan {
  perSkillOutputs: { skill: Skill; result: CompileResult }[];
  aggregatedOutputs: { target: SupportedTarget; path: string; content: string; sections: number }[];
  lockfile: Lockfile;
  skippedCount: number;
}

function loadSkills(files: string[]): { sources: SkillSource[]; parseError: boolean } {
  const sources: SkillSource[] = [];
  let parseError = false;
  for (const file of files) {
    try {
      const skill = parseSkillFile(file);
      const sourceBytes = readFileSync(file);
      sources.push({ skill, sourceBytes });
    } catch (err) {
      console.error(kleur.red("✗ Failed to parse"), file);
      console.error(kleur.dim(String(err)));
      parseError = true;
    }
  }
  return { sources, parseError };
}

// Targets that aggregate every skill into a single shared file.
const AGGREGATED_META: Partial<Record<SupportedTarget, { path: string; header: string }>> = {
  codex: {
    path: "AGENTS.md",
    header: `# AGENTS\n\n_Generated by [crosskill](https://crosskill.dev). Do not edit by hand — edit \`./crosskill/*.skill.md\` instead._\n\n`,
  },
  copilot: {
    path: ".github/copilot-instructions.md",
    header: `# Copilot instructions\n\n_Generated by [crosskill](https://crosskill.dev). Do not edit by hand — edit \`./crosskill/*.skill.md\` instead._\n\n`,
  },
};

/**
 * Compile every skill to every enabled target, in memory. Returns the plan
 * (output paths + content + lockfile data) without touching disk.
 */
export function planBuild(sources: SkillSource[], cwd: string): BuildPlan {
  const perSkillOutputs: BuildPlan["perSkillOutputs"] = [];
  const aggregatedSections: Partial<Record<SupportedTarget, string[]>> = {};
  const lockSkills: Record<string, SkillLockEntry> = {};
  let skippedCount = 0;

  for (const { skill, sourceBytes } of sources) {
    const enabled = skill.frontmatter.targets ?? {};
    const lockEntry: SkillLockEntry = {
      version: skill.frontmatter.version,
      sourceHash: sha256(sourceBytes),
      outputs: {},
    };
    for (const target of Object.keys(enabled) as SupportedTarget[]) {
      if (!enabled[target]) continue;
      const compiler = COMPILERS[target];
      if (!compiler) {
        skippedCount++;
        continue;
      }
      const result = compiler.compile(skill, cwd);

      if (AGGREGATED_META[target]) {
        (aggregatedSections[target] ??= []).push(result.content);
      } else {
        perSkillOutputs.push({ skill, result });
      }
      lockEntry.outputs[target] = {
        path: toPosixPath(relative(cwd, result.outputPath)),
        contentHash: sha256(result.content),
      };
    }
    lockSkills[skill.frontmatter.name] = lockEntry;
  }

  const aggregatedOutputs: BuildPlan["aggregatedOutputs"] = [];
  const lockAggregated: Lockfile["aggregated"] = {};
  for (const [target, sections] of Object.entries(aggregatedSections) as [
    SupportedTarget,
    string[],
  ][]) {
    if (!sections || sections.length === 0) continue;
    const meta = AGGREGATED_META[target];
    if (!meta) continue;
    const content = meta.header + sections.join("\n---\n\n");
    aggregatedOutputs.push({ target, path: meta.path, content, sections: sections.length });
    lockAggregated[target] = {
      path: toPosixPath(meta.path),
      contentHash: sha256(content),
      sections: sections.length,
    };
  }

  return {
    perSkillOutputs,
    aggregatedOutputs,
    skippedCount,
    lockfile: {
      lockfileVersion: LOCKFILE_VERSION,
      crosskillVersion: CROSSKILL_VERSION,
      skills: lockSkills,
      aggregated: lockAggregated,
    },
  };
}

function writeOut(result: CompileResult): void {
  mkdirSync(dirname(result.outputPath), { recursive: true });
  writeFileSync(result.outputPath, result.content, "utf8");
}

function printDrift(drift: LockDrift[]): void {
  for (const d of drift) {
    console.error(kleur.red("✗"), d.message);
  }
}

/**
 * Run a full build: parse every skill, compile to every enabled target, write
 * outputs, then update `crosskill.lock`. Aggregated targets (AGENTS.md,
 * copilot-instructions.md) collapse multiple skills into one file.
 *
 * `--frozen` (CI mode): compute everything in memory, compare to lockfile,
 * exit non-zero on drift. Does not write files.
 */
export async function buildCommand(opts: BuildOptions = {}): Promise<void> {
  const cwd = opts.cwd ?? process.cwd();
  const config = loadConfig(cwd);
  const skillsDir = join(cwd, config.skillsDir);

  const files = findSkillFiles(skillsDir);
  if (files.length === 0) {
    console.log(
      kleur.yellow(
        `No skills found in ${config.skillsDir}. Run ${kleur.cyan("crosskill init")} first.`
      )
    );
    return;
  }

  const { sources, parseError } = loadSkills(files);
  if (parseError) process.exitCode = 1;

  const plan = planBuild(sources, cwd);

  if (opts.frozen) {
    const locked = readLockfile(cwd);
    if (!locked) {
      console.error(
        kleur.red("✗ No crosskill.lock found."),
        `Run ${kleur.cyan("crosskill build")} to generate one before using ${kleur.cyan("--frozen")}.`
      );
      process.exitCode = 1;
      return;
    }
    const drift = diffLockfiles(plan.lockfile, locked);
    if (drift.length === 0) {
      console.log(
        kleur.green().bold("✓ crosskill.lock is up to date."),
        kleur.dim(`(${sources.length} skill(s) verified)`)
      );
      return;
    }
    console.error(
      kleur.red().bold(`✗ ${drift.length} drift(s) vs ${LOCKFILE_NAME}:`)
    );
    printDrift(drift);
    console.error();
    console.error(
      kleur.dim("Run"),
      kleur.cyan("crosskill build"),
      kleur.dim("locally to update the lockfile.")
    );
    process.exitCode = 1;
    return;
  }

  for (const { skill, result } of plan.perSkillOutputs) {
    writeOut(result);
    console.log(
      kleur.green("✓"),
      kleur.dim(skill.frontmatter.name + " →"),
      toPosixPath(relative(cwd, result.outputPath))
    );
  }

  for (const agg of plan.aggregatedOutputs) {
    const outPath = join(cwd, agg.path);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, agg.content, "utf8");
    console.log(
      kleur.green("✓"),
      kleur.dim(`${agg.path}  (${agg.target},`),
      kleur.dim(`${agg.sections} sections)`)
    );
  }

  writeLockfile(cwd, plan.lockfile);
  console.log(kleur.green("✓"), kleur.dim(LOCKFILE_NAME));

  const writtenCount = plan.perSkillOutputs.length + plan.aggregatedOutputs.length;
  console.log();
  console.log(
    kleur.bold().green(`Built ${sources.length} skill(s) → ${writtenCount} output file(s).`)
  );
  if (plan.skippedCount > 0) {
    console.log(kleur.dim(`  (skipped ${plan.skippedCount} target(s) without a compiler yet)`));
  }
}
