import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import kleur from "kleur";
import { parseSkillFile } from "../parser.js";
import { COMPILERS } from "../compilers/index.js";
import type { CompileResult, Skill, SupportedTarget } from "../schema.js";

interface BuildOptions {
  cwd?: string;
  configPath?: string;
}

interface CrosskillConfig {
  skillsDir: string;
  outputs?: Partial<Record<SupportedTarget, string>>;
}

function loadConfig(cwd: string): CrosskillConfig {
  const configPath = join(cwd, "crosskill.config.json");
  if (!existsSync(configPath)) {
    return { skillsDir: "./crosskill" };
  }
  const raw = readFileSync(configPath, "utf8");
  return JSON.parse(raw) as CrosskillConfig;
}

function findSkillFiles(skillsDir: string): string[] {
  if (!existsSync(skillsDir)) return [];
  const files: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile() && entry.name.endsWith(".skill.md")) {
        files.push(full);
      } else if (entry.isFile() && entry.name === "skill.md") {
        files.push(full);
      }
    }
  };
  walk(skillsDir);
  return files.sort();
}

function writeOut(result: CompileResult): void {
  mkdirSync(dirname(result.outputPath), { recursive: true });
  writeFileSync(result.outputPath, result.content, "utf8");
}

/**
 * Run a full build: parse every skill in skillsDir and compile to every
 * enabled target. AGENTS.md (codex) is special — multiple skills are
 * concatenated into one file.
 */
export async function buildCommand(opts: BuildOptions = {}): Promise<void> {
  const cwd = opts.cwd ?? process.cwd();
  const config = loadConfig(cwd);
  const skillsDir = join(cwd, config.skillsDir);

  const files = findSkillFiles(skillsDir);
  if (files.length === 0) {
    console.log(
      kleur.yellow(
        `No skills found in ${config.skillsDir}. Run ${kleur.cyan("crosskill init")} first.`
      )
    );
    return;
  }

  const skills: Skill[] = [];
  for (const file of files) {
    try {
      skills.push(parseSkillFile(file));
    } catch (err) {
      console.error(kleur.red("✗ Failed to parse"), file);
      console.error(kleur.dim(String(err)));
      process.exitCode = 1;
    }
  }

  const codexSections: string[] = [];
  let writtenCount = 0;
  let skippedCount = 0;

  for (const skill of skills) {
    const enabled = skill.frontmatter.targets ?? {};
    for (const target of Object.keys(enabled) as SupportedTarget[]) {
      if (!enabled[target]) continue;
      const compiler = COMPILERS[target];
      if (!compiler) {
        skippedCount++;
        continue;
      }
      const result = compiler.compile(skill, cwd);

      if (target === "codex") {
        codexSections.push(result.content);
      } else {
        writeOut(result);
        writtenCount++;
        console.log(
          kleur.green("✓"),
          kleur.dim(skill.frontmatter.name + " →"),
          result.outputPath.replace(cwd + "\\", "").replace(cwd + "/", "")
        );
      }
    }
  }

  // Emit AGENTS.md (one file, all skills as sections)
  if (codexSections.length > 0) {
    const agentsPath = join(cwd, "AGENTS.md");
    const header = `# AGENTS\n\n_Generated by [crosskill](https://crosskill.dev). Do not edit by hand — edit \`./crosskill/*.skill.md\` instead._\n\n`;
    writeFileSync(agentsPath, header + codexSections.join("\n---\n\n"), "utf8");
    writtenCount++;
    console.log(kleur.green("✓"), kleur.dim("AGENTS.md  (codex,") , kleur.dim(`${codexSections.length} sections)`));
  }

  console.log();
  console.log(
    kleur.bold().green(`Built ${skills.length} skill(s) → ${writtenCount} output file(s).`)
  );
  if (skippedCount > 0) {
    console.log(kleur.dim(`  (skipped ${skippedCount} target(s) without a compiler yet)`));
  }
}
